### ISSUE TITLE
display-time-mode not given enough space

### ISSUE THREAD

**Issue by ajschumacher** [Bruce-Connor/smart-mode-line#113]
Hello! With `(display-time-mode t)` I get the following:

![screen shot 2015-01-25 at 12 34 16 am](https://cloud.githubusercontent.com/assets/1071322/5890462/18ccae1c-a42a-11e4-8886-34a103fd44d3.png)

The time is pushed off the right hand side. It doesn't fit until I have the frame 87 columns wide, which is 7 wider than I'd rather have it. Is there an easy way for me to resolve this? Seems like there's a lot of space in the middle, but I don't know how to tweak effectively yet. Thanks!

**Comment by Bruce-Connor** [comment]
Looking at your mode-line, the best option is to decrease the value of `sml/name-width` (mine is 25). That will save you a lot of space.

If you want to *really* minimize space usage, you can even set that variable to `0`, and set `sml/shorten-directory` to nil.

**Comment by ajschumacher** [comment]
Thanks! It sounds like this isn't an issue for the project then; I'll close. Thanks for the help!

**Comment by Bruce-Connor** [comment]
No problem. Glad to help.
