### ISSUE TITLE
sml/replacer-regexp-list Defaults.

### ISSUE THREAD

**Issue by ianbarton** [Bruce-Connor/smart-mode-line#114]
This is a minor niggle, but perhaps the defaults of sml/replacer-regexp-list should be more clearly explained in the README. I was trying to add:

    (add-to-list 'sml/replacer-regexp-list '("^:~Documents/emacs/org/org_files" ":Org:") t)

which didn't work as expected because "^:~Documents is already defined in the default list and I was appending my stuff to the end of the list. After reading the code the following works as I expected:

    (add-to-list 'sml/replacer-regexp-list '("^:Doc:emacs/org/org_files" ":Org:") t)

**Comment by Bruce-Connor** [comment]
That's a good point. I'll try to expand that part of the readme. Would you like to suggest a bit of text to be added?

**Comment by ianbarton** [comment]
How about:

The following abbreviations are already defined:

    ("^~/\\.emacs\\.d/" ":ED:")
    ("^/sudo:.*:" ":SU:")
    ("^~/Documents/" ":Doc:")
    ("^~/Dropbox/" ":DB:")
    ("^:\\([^:]*\\):Documento?s/" ":\\1/Doc:")
    ("^~/[Gg]it/" ":Git:")
    ("^~/[Gg]it[Hh]ub/" ":Git:")
    ("^~/[Gg]it\\([Hh]ub\\|\\)-?[Pp]rojects/" ":Git:"))

You can add abbreviations sequentially to the predefined list, or to your own lists,  by
adding them in order:

;; Added in the right order, they even work sequentially:
(add-to-list 'sml/replacer-regexp-list '("^:DB:Documents" ":DDocs:") t)
(add-to-list 'sml/replacer-regexp-list '("^~/Git-Projects/" ":Git:") t)
(add-to-list 'sml/replacer-regexp-list '("^:Git:\\(.*\\)/src/main/java/" ":G/\\1/SMJ:") t)

Note the "t" option ensures that your customizations are added to the
end of the list, which enables stacking of customizations.

However, if you want to override one of the pre-defined  abbreviations with your
own definition you need to add your customization to the start of the list (note the
ommited "t"):

(add-to-list 'sml/replacer-regexp-list '("^~/Dropbox/" ":DBox:") )

**Comment by Bruce-Connor** [comment]
Added it in. Thanks for the suggestion!
