### ISSUE TITLE
Display Git prefix of vc-mode in mode-line

### ISSUE THREAD

**Issue by xyalan** [Bruce-Connor/smart-mode-line#115]
By default, Emacs displays `Git-master` in the mode-line when I am working in a directory that is under the Git version control system.

Now smart-mode-line removing the `Git` prefix, and emacs display `:master` in the mode-line. I want to get the `Git` prefix back again! How can I configure? Thanks!

**Comment by Bruce-Connor** [comment]
Yes, There's a variable to disable this hiding. I'll check the name when I'm at the computer.

**Comment by Bruce-Connor** [comment]
The variable is `sml/vc-mode-show-backend`. Just set it to t:

    (setq sml/vc-mode-show-backend t)

**Comment by Bruce-Connor** [comment]
I'll close this for now, but let me know if that's what you were looking for.

**Comment by xyalan** [comment]
Yes, that's what I wanna.Thank you!
