### ISSUE TITLE
SML causes empty buffers when opening from Windows Explorer

### ISSUE THREAD

**Issue by ReneFroger** [Bruce-Connor/smart-mode-line#118]
In Windows Explorer, you could open a text file with Emacs. Lately I noticed then my Emacs buffer is empty. There is no file loaded, when I open it with Emacs. 

When I comment the following code out in my dot-emacs: 

```
(add-hook 'after-init-hook 'sml/setup)
(add-hook 'after-init-hook 'sml/apply-theme 'dark)
```
And test it again, I open a file from Windows Explorer with Emacs, then I see the contents again in the buffer. What caused this issue? 

I use Emacs 25.1 (bleeding edge version), under Windows 7 x64 by the way.

**Comment by Bruce-Connor** [comment]
Hi there. 
Could you try removing the second line? 

As I've explained before, that line does not do what you think it does. The `add-hook` function does not pass arguments to the function it's hooking.
Let me know if you still have that problem after removing the second line.

**Comment by ReneFroger** [comment]
You're right again. 

When I remove the second line, this issue will not occur. But I couldn't figure out how the second line could cause this weird issue, even when Emacs is running fine without any mention of error. 

Sorry for the inconvenience. Your help is appreciated!

**Comment by Bruce-Connor** [comment]
I'm not entirely sure why it happens either =/, I'll try to figure out if it's sml's fault.

**Comment by Bruce-Connor** [comment]
Now that I think about it. You probably had an error message lying somewhere because `sml/apply-theme` can't be called with no arguments (and that's what happens when you hook it). So that's probably why things weren't behaving right.

**Comment by ReneFroger** [comment]
That could be an explaination. But I find it weird that Emacs don't give me any error, and still work fine, but with empty file. But thanks for the thinking.                                                                                                                                                                                                                 Van: Artur MalabarbaVerzonden: donderdag 5 maart 2015 12:45Aan: Bruce-Connor/smart-mode-lineBeantwoorden: Bruce-Connor/smart-mode-lineCc: ReneFrogerOnderwerp: Re: [smart-mode-line] SML causes empty buffers when opening from Windows Explorer (#118)Now that I think about it. You probably had an error message lying somewhere because sml/apply-theme can't be called with no arguments (and that's what happens when you hook it). So that's probably why things weren't behaving right.

—Reply to this email directly or view it on GitHub.

**Comment by Bruce-Connor** [comment]
> That could be an explaination. But I find it weird that Emacs don't give me any error, and still work fine, but with empty file. 

Well, that's the thing, it wasn't working fine. :-)
And you probably just didn't notice the error for some other reason. If add an invalid function to my `after-init-hook` I get an error in the messages buffer (`C-h e`).
