### ISSUE TITLE
Suggestion: sml vs. smart-mode-line is confusing

### ISSUE THREAD

**Issue by alphapapa** [Bruce-Connor/smart-mode-line#121]
This is a minor suggestion: I know `sml` looks cleaner, but after installing the package, looking for `smart-mode-line` commands came up empty.  It was non-obvious that I needed to look for `sml`.

Yes, of course, it's in the installation instructions.  :)  But many packages are usable without even having to look up the instructions, because their activate/enable/setup command is something like `name-of-package-enable`.

Just a thought.  :)  Thanks.

**Comment by Bruce-Connor** [comment]
It's a nice thought. I'll do it when I get a chance. Thanks!
